export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_SUCCESS = 200;
export const STATUS_CODE_CONFLICT = 409;
export const STATUS_CODE_WRONG_CREDENTIALS = 401;
export const STATUS_CODE_NOT_AUTHORISED = 401;
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;
