name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    ENV: PROD
    CHAT_MONGO_IP: 127.0.0.1
    CHAT_MONGO_PORT: 27017
    USER_REDIS_PORT: 6379
    USER_REDIS_IP: 127.0.0.1
    USER_MONGO_IP: 127.0.0.1
    USER_MONGO_PORT: 27017

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 3

        strategy:
            matrix:
                node-version: ["18.x"]
                mongodb-version: ["6.0"]
                redis-version: [4]

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Start Redis
              uses: supercharge/redis-github-action@1.4.0
              with:
                  redis-version: ${{ matrix.redis-version }}

            - run: npm ci
              working-directory: chat-service

            - run: npm run build --if-present
              working-directory: chat-service

            - run: npm test
              working-directory: chat-service
              env:
                  CI: true

            - run: npm ci
              working-directory: user-service

            - run: npm run build --if-present
              working-directory: user-service

            - run: npm test
              working-directory: user-service
              env:
                  CI: true
