name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENV: PROD
  CHAT_MONGO_IP: 127.0.0.1
  CHAT_MONGO_PORT: 27017
  QN_MONGO_IP: 127.0.0.1
  QN_MONGO_PORT: 5200

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: ['18.x']
        mongodb-version: ['6.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm ci
      working-directory: chat-service
    
    - run: docker rename mongodb chat-service-mongodb
    
    - name: Start Question Service MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 5100

    - run: npm run build --if-present
      working-directory: chat-service

    - run: npm test
      working-directory: chat-service

    - run: npm ci
      working-directory: question-service

    - run: npm run build --if-present
      working-directory: question-service

    - run: npm run seed --if-present
      working-directory: question-service

    - run: npm test
      working-directory: question-service
      env:
        CI: true