name: CollaborationService CD

on:
  push:
    branches: [ main ]
    paths:
      - collaboration-service/**
      - .github/workflows/collabservice-CD.yml

env:
  REDIS_IP: ${{secrets.COLLAB_REDIS_IP}}
  REDIS_PORT: ${{secrets.COLLAB_REDIS_PORT}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cs3219g2/collabservice:latest
          context: "{{defaultContext}}:collaboration-service"