name: Frontend CI

on:
  push:
    branches: [ main, feature/CI/CD ]
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - frontend/**

env:
  REACT_APP_QN_SERVER_IP: ${{secrets.QN_SERVER_IP}}
  REACT_APP_QN_SERVER_PORT: ${{secrets.QN_SERVER_PORT}}
  REACT_APP_USER_SERVER_IP: ${{secrets.USER_SERVER_IP}}
  REACT_APP_USER_SERVER_PORT: ${{secrets.USER_SERVER_PORT}}
  REACT_APP_MATCH_SERVER_IP: ${{secrets.MATCH_SERVER_IP}}
  REACT_APP_MATCH_SERVER_PORT: ${{secrets.MATCH_SERVER_IP}}
  REACT_APP_COLLAB_SERVER_IP: ${{secrets.COLLAB_SERVER_IP}}
  REACT_APP_COLLAB_SERVER_PORT: ${{secrets.COLLAB_SERVER_IP}}
  REACT_APP_CHAT_SERVER_IP: ${{secrets.CHAT_SERVER_IP}}
  REACT_APP_CHAT_SERVER_PORT: ${{secrets.CHAT_SERVER_IP}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
          context: ./frontend