name: QuestionService CD

on:
  push:
    branches: [ main, feature/CI/CD ]
    paths:
      - question-service/**
      - .github/workflows/questionservice-CD.yml
  pull_request:
    branches: [ main, feature/CI/CD  ]
    paths:
      - question-service/**
      - .github/workflows/questionservice-CD.yml

env:
  QN_MONGO_IP: ${{secrets.QN_MONGO_IP}}
  QN_MONGO_PORT: ${{secrets.QN_MONG_PORT}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cs3219g2/questionservice:latest
          context: "{{defaultContext}}:question-service"