name: UserService CD

on:
  push:
    branches: [ main ]
    paths:
      - user-service/**
      - .github/workflows/userservice-CD.yml
  pull_request:
    branches: [ main ]
    paths:
      - user-service/**
      - .github/workflows/userservice-CD.yml

env:
  ENV: PROD
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  DB_CLOUD_URI: mongodb://host.docker.internal:27017/
  MONGO_IP: ${{secrets.USER_MONGO_IP}}
  MONGO_PORT: ${{secrets.USER_MONGO_PORT}}
  REDIS_IP: ${{secrets.USER_REDIS_IP}}
  REDIS_PORT: ${{secrets.USER_REDIS_PORT}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cs3219g2/userservice:latest
          context: "{{defaultContext}}:user-service"